### ISSUE TITLE
"Refactorings - Refactoring Basics" has wrong selections

### ISSUE THREAD

**Issue by sloshy** [JetBrains/ide-features-trainer#15]
Once I got to the "Refactoring Basics" page, it feels like all of the selections are completely off. I'm running IntelliJ IDEA 2016.3 on Windows 10 x64. Here is an example screenshot that shows what I mean. The last step in particular is broken for me because it gets rid of the "new FileReader" code in the third step and moves the caret to the upper-left corner.

<img width="960" alt="idea_2016-12-15_15-30-08" src="https://cloud.githubusercontent.com/assets/427237/21242882/0f48b23c-c2dc-11e6-876f-d002c362be5a.png">

**Comment by sloshy** [comment]
Also it seems that the final step of "Editor Coding Assistance" has a similar issue. Seems that the caret isn't placing itself correctly in some instances.

<img width="960" alt="idea_2016-12-15_15-50-56" src="https://cloud.githubusercontent.com/assets/427237/21243408/54fd3364-c2de-11e6-9025-7e18b22d72cb.png">

**Comment by sajjadpz** [comment]
In IntelliJ IDEA 2016.2 for mac the last step is not marked as completed even if it has been completed successfully and you will have to skip it to move to next lesson.
<img width="1000" alt="screen shot 2016-12-20 at 6 16 50 pm" src="https://cloud.githubusercontent.com/assets/9335671/21351866/b4a72c42-c6e0-11e6-961c-a67e05585419.png">
