### ISSUE TITLE
Code Assistance - Quick Popup , last instruction is not working.

### ISSUE THREAD

**Issue by sajjadpz** [JetBrains/ide-features-trainer#17]
I'm using IntelliJ IDEA 2016.2 for mac.
The last instruction that says "see the definition of the symbol at the caret"  is not functional. I have to skip this Lesson in order to navigate to next lesson.
<img width="385" alt="screen shot 2016-12-20 at 6 42 12 pm" src="https://cloud.githubusercontent.com/assets/9335671/21352598/0ceb0646-c6e4-11e6-8a8d-8d43f9b53c71.png">

**Comment by karashevich** [comment]
Sorry, it should work in the last versions.
