### ISSUE TITLE
Support loading lesson artifacts hosted within company network

### ISSUE THREAD

**Issue by kodeninja** [JetBrains/ide-features-trainer#18]
Would it be possible to host lessons (XMLs) within company network (perhaps in source control/wiki etc), and then somehow register them with the Trainer plugin?

This could be super useful for in-house platform/framework developers who can provide these lessons to other teams that build applications on these platforms and leverage IDEA to do so.

**Comment by karashevich** [comment]
@kodeninja sorry for a long reply. What language do you need to use (Java, Python, Kotlin) for this kind of lessons?
