### ISSUE TITLE
Folding lesson: it is said that the expression is collapsed to a lambda, while it is not

### ISSUE THREAD

**Issue by Victoria-Dumova** [JetBrains/ide-features-trainer#28]
0.8.54

Step two says that new Runnable() {...} is collapsed to a lambda function, while it is just collapsed.

(We have "Replace with lambda" intention, and this one really results in a lambda)

**Comment by karashevich** [comment]
Thank you, it is turned off for a while. We'll try to change lesson according to this ambiguous behavior of the lesson in different environments.
