### ISSUE TITLE
Updating this plugins destroys my IntelliJ config!

### ISSUE THREAD

**Issue by mkurz** [JetBrains/ide-features-trainer#56]
I just updated IntelliJ to latest 2019.3. All my recent projects were gone. I tried to find out how this happend and it boiled down to this plugin:
First when upgrading IntelliJ but not updating any plugins yet, everything is fine. As soon as I updated all my plugins (in one step), all my recent projects were gone. To find out which plugin causes that, I deleted my `$HOME/.IntelliJIdea2019.3/config/` folder, re-imported the config from `$HOME/.IntelliJIdea2019.2/config/` and afterwards updated the plugins one after another. All plugins updated without any problems, leaving IntelliJ intact. However as soon as I updated the IDE features trainer and restarted the IDE booom, (at least) recent projects were gone, maybe even more configs (I did not check). Here is a screenshot:
![image](https://user-images.githubusercontent.com/644927/69922638-5dd74a00-149e-11ea-91f6-7e085eff5d35.png)

**Comment by artspb** [comment]
I'm sorry to hear that you lost your config. Could you please clarify what do you mean by "All my recent projects were gone?" Didn't you see them in the UI or did they disappear from the config files?

**Comment by karashevich** [comment]
Sorry for this inconvenience, this is indeed a problem with the last plugins's update. Recent projects should be left intact, the problem is that the other storage for recent projects is using `recentProjectDirectories.xml`. Disabling the plugin should help with restoring recent projects. We are working on the fix, the most likely it will be available with the next IDEA update (2019.3.1).

**Comment by mkurz** [comment]
@karashevich Thanks, looking forward to the fix.

**Comment by karashevich** [comment]
Fix has been uploaded to [JetBrains plugin repo](https://plugins.jetbrains.com/plugin/8554-ide-features-trainer/update/73561). This should restore recent projects from the previous version.

**Comment by mkurz** [comment]
@karashevich Thanks, I just updated and it worked :tada:
